#!/usr/bin/env python3
"""Stage 2 age engine v2 -- synthetic twins: the only way to MEASURE an age engine's accuracy.

There is one real slick in the library with a documented release time (Huntington, 2.8 h).
One is not a validation set. So the accuracy claim is made on twins: slicks simulated with a
KNOWN age through the REAL current and wind fields of the six cases, turned into SAR-like
polygons, and handed to the real engine as if Stage 1 had detected them.

    python pipeline/drift/age_twins.py make      --field case-jacksonville-2024 --n 24
    odenv\\Scripts\\python pipeline/drift/opendrift_twins.py --field case-jacksonville-2024
    python pipeline/drift/age_twins.py prepare   --field case-jacksonville-2024
    odenv\\Scripts\\python pipeline/drift/opendrift_age.py --case case-jacksonville-2024 --batch
    python pipeline/drift/age_twins.py score     --field case-jacksonville-2024 --jobs 7
    python pipeline/drift/age_twins.py calibrate                # all fields -> age_calibration.json
    python pipeline/drift/age_twins.py report                   # -> docs/evaluation/stage2-age-engine.md

THE INVERSE CRIME, AND HOW THIS AVOIDS IT
    Scoring a model on data it generated itself measures nothing but its own noise. Half the
    twins are generated by OUR model and half by OpenDrift OpenOil, and three scores are kept:

      cross_ours     OpenOil truths, scored with our model only (E1 + E4)
      cross_openoil  our truths, scored with OpenOil only (E2 + E4)
      mixture        every twin, scored the way production scores (E1 (+) E2, E3, E4)

    The observation-error sigmas are fitted on the two CROSS settings only. The mixture number
    is reported beside them and is expected to be the most flattering of the three.

TRUTH PARAMETERS ARE DRAWN WIDER THAN THE ENGINE ASSUMES
    Truth diffusivity is Okubo's K at the scale the twin actually reaches, times a lognormal
    factor of x/ 4 -- wider than the x/ 3 the engine assumes -- so the engine's K prior is
    deliberately a little wrong, as it will be on a real slick. (A first draft drew K
    log-uniformly over [0.05, 100]; that made age and K fully degenerate and is physically
    unrealistic for km-scale patches. See age.okubo_member_ks.) Truth age is log-uniform on
    [1.5, 66] h, matching the engine's log-uniform prior, so coverage is measured under the
    distribution the posterior claims to describe.

Everything expensive is stored (candidate shape curves per twin), so `calibrate` refits sigmas
and weights in seconds without rerunning a single particle.
"""
import argparse
import json
import math
import random
import sys
import time
from datetime import timedelta
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(HERE))

import age                                        # noqa: E402
import age_posterior as AP                        # noqa: E402

TWINS = HERE / "out" / "twins"
FIELDS = ["case-farallones-2023", "case-gulf-alaska-2023", "case-huntington-2021",
          "case-jacksonville-2024", "case-jamnagar-2024", "case-mumbai-2023"]
TRUTH_AGE_H = (1.5, 66.0)
TRACK_FRACTION = 0.3
CANDIDATES = "2:72:4"
SCORE_MEMBERS = 12
SCORE_PARTICLES = 1200
# Stage 1's discharge rule, restated (detect/ships.py:classify_discharge -- no cross-stage
# import, by the architecture rule). Twins must be labelled the way real detections are.
CHRONIC_ELONGATION, ACUTE_ELONGATION, STRAIGHTNESS_MIN = 5.0, 3.0, 0.60


def loguniform(rng, lo, hi):
    return float(math.exp(rng.uniform(math.log(lo), math.log(hi))))


def parse_ts(s):
    from datetime import datetime
    return datetime.fromisoformat(str(s).replace("Z", "+00:00"))


def case_anchor(field_case):
    """t0 and the case's own slick centroid -- twins are released around where real oil was."""
    from slick import merge_oil_features
    cdir = REPO / "cases" / field_case
    meta = json.loads((cdir / "meta.json").read_text())
    feat, _ = merge_oil_features(json.loads((cdir / "detections.geojson").read_text()))
    return parse_ts(meta["detection_time"]), tuple(feat["properties"]["centroid"])


# ---------------------------------------------------------------------------------------
# particles -> a SAR-like polygon
# ---------------------------------------------------------------------------------------

def particles_to_feature(pos, feature_id, thresh_frac=0.2, smooth_px=1.5, min_px_m=20.0):
    """The polygon Stage 1 would have drawn around this cloud, or None if nothing is visible.

    Density on a local metric grid, gaussian-smoothed, thresholded at `thresh_frac` of its peak
    (SAR sees where oil is thick enough to damp waves, not where the last particle went),
    largest connected component, vectorised. Pixel size adapts to the cloud so a 2000-particle
    cloud is neither a speckle field nor one blocky pixel.
    """
    from scipy.ndimage import gaussian_filter, label
    from rasterio.features import shapes
    from rasterio.transform import Affine

    p = np.asarray(pos, dtype=np.float64)
    p = p[np.all(np.isfinite(p), axis=1)]
    if p.shape[0] < 30:
        return None
    lon0, lat0 = float(np.median(p[:, 0])), float(np.median(p[:, 1]))
    xy = age._local_metres(p, lon0, lat0)
    # Pixel size from LOCAL particle spacing (median distance to the 8th neighbour), not from
    # the whole cloud's spread: a 50 km curving ship track has a km-scale PCA minor axis, and
    # pixels sized from that are wider than the track itself -- which inflated a 0.7 km-wide
    # twin into a 75 km2 blob and would have fed the width estimator a width set by the grid.
    from scipy.spatial import cKDTree
    d8 = float(np.median(cKDTree(xy).query(xy, k=9)[0][:, -1]))
    px = float(np.clip(0.6 * d8, min_px_m, 400.0))
    lo_xy = xy.min(axis=0) - 6 * px
    hi_xy = xy.max(axis=0) + 6 * px
    nx = int(math.ceil((hi_xy[0] - lo_xy[0]) / px))
    ny = int(math.ceil((hi_xy[1] - lo_xy[1]) / px))
    if nx * ny > 16_000_000:
        return None
    H, _, _ = np.histogram2d(xy[:, 1], xy[:, 0], bins=[ny, nx],
                             range=[[lo_xy[1], lo_xy[1] + ny * px], [lo_xy[0], lo_xy[0] + nx * px]])
    H = gaussian_filter(H[::-1, :], smooth_px)          # row 0 = north
    mask = H >= thresh_frac * H.max()
    lab, n = label(mask)
    if n == 0:
        return None
    big = lab == (1 + int(np.argmax(np.bincount(lab.ravel())[1:])))
    tr = Affine(px, 0.0, lo_xy[0], 0.0, -px, lo_xy[1] + ny * px)
    ring = None
    for geom, val in shapes(big.astype("uint8"), mask=big, transform=tr):
        if val == 1:
            ring = np.asarray(geom["coordinates"][0], dtype=np.float64)
            break
    if ring is None or ring.shape[0] < 4:
        return None
    coslat = math.cos(math.radians(lat0))
    lonlat = np.column_stack([lon0 + ring[:, 0] / (coslat * age.KM_PER_DEG_LAT * 1e3),
                              lat0 + ring[:, 1] / (age.KM_PER_DEG_LAT * 1e3)])
    area_km2 = float(big.sum()) * px * px / 1e6
    L, d = age.polygon_major_axis_km(lonlat)
    elong = max(1.0, (d.get("bbox_aspect") or 1.0))
    axis = L if L else 0.0
    perim = float(np.sum(np.hypot(np.diff(ring[:, 0]), np.diff(ring[:, 1])))) / 1000.0
    straight = float(np.clip(2.0 * axis / perim, 0.0, 1.0)) if perim > 0 else 1.0
    if elong >= CHRONIC_ELONGATION:
        dc = "chronic" if straight >= STRAIGHTNESS_MIN else "unknown"
    elif elong < ACUTE_ELONGATION:
        dc = "acute"
    else:
        dc = "unknown"
    rr, cc = np.nonzero(big)
    cx = lo_xy[0] + (cc.mean() + 0.5) * px
    cy = lo_xy[1] + ny * px - (rr.mean() + 0.5) * px
    centroid = [round(lon0 + cx / (coslat * age.KM_PER_DEG_LAT * 1e3), 5),
                round(lat0 + cy / (age.KM_PER_DEG_LAT * 1e3), 5)]
    return {"type": "Feature",
            "geometry": {"type": "Polygon",
                         "coordinates": [np.round(lonlat, 6).tolist()]},
            "properties": {"id": feature_id, "classification": "oil", "confidence": 1.0,
                           "area_km2": round(area_km2, 4), "elongation": round(elong, 2),
                           "shape_class": "linear" if elong > 3 else "blob",
                           "discharge_class": dc, "centroid": centroid,
                           "twin_px_m": round(px, 1)}}


# ---------------------------------------------------------------------------------------
# make: draw truths, simulate ours
# ---------------------------------------------------------------------------------------

def draw_truths(field_case, n, seed, field_bbox, anchor):
    rng = np.random.default_rng(seed)
    out = []
    for i in range(n):
        kind = "track" if rng.random() < TRACK_FRACTION else "patch"
        gen = "ours" if i % 2 == 0 else "openoil"
        # release within 12 km of the real slick, kept 60 km inside the field box
        for _ in range(100):
            r = 12.0 * math.sqrt(rng.random())
            th = rng.uniform(0, 2 * math.pi)
            lon = anchor[0] + r * math.cos(th) / (age.KM_PER_DEG_LAT * math.cos(math.radians(anchor[1])))
            lat = anchor[1] + r * math.sin(th) / age.KM_PER_DEG_LAT
            if field_bbox is None:
                break
            w, s, e, nth = field_bbox
            pad = 60.0 / age.KM_PER_DEG_LAT
            if w + pad < lon < e - pad and s + pad < lat < nth - pad:
                break
        t = {"id": f"{field_case}-t{i:03d}", "field": field_case, "generator": gen,
             "kind": kind, "age_h": round(loguniform(rng, *TRUTH_AGE_H), 3),
             "release": [round(lon, 5), round(lat, 5)],
             "wind_coeff": round(float(rng.uniform(0.025, 0.035)), 4),
             "current_scale": round(float(np.clip(rng.normal(1.0, 0.15), 0.5, 1.5)), 3),
             "sigma0_m": round(float(rng.uniform(50.0, 400.0)), 1),
             "oil_type": ["GENERIC MEDIUM CRUDE", "GENERIC INTERMEDIATE FUEL OIL 180",
                          "GENERIC DIESEL"][int(rng.integers(3))],
             "seed": int(rng.integers(1 << 30))}
        if kind == "track":
            t["ship_speed_ms"] = round(float(rng.uniform(3.0, 7.0)), 2)
            t["heading_deg"] = round(float(rng.uniform(0.0, 360.0)), 1)
            t["discharge_h"] = round(float(min(rng.uniform(0.5, 3.0), 0.8 * t["age_h"])), 3)
            t["sigma0_m"] = round(float(rng.uniform(10.0, 30.0)), 1)
        # Truth K: Okubo at the scale this twin will actually reach, times a lognormal factor
        # WIDER than the engine assumes (x/ TRUTH_K_SPREAD vs age.TRACK_OKUBO_SPREAD), so the
        # engine's prior is deliberately a little wrong -- as it will be on a real slick.
        f = math.exp(math.log(TRUTH_K_SPREAD) * rng.normal())
        t["K_m2s"] = round(truth_diffusivity(t["age_h"], t["sigma0_m"], f), 4)
        t["K_factor"] = round(f, 3)
        out.append(t)
    return out


TRUTH_K_SPREAD = 4.0


def truth_diffusivity(age_h, sigma0_m, factor):
    """K = factor x Okubo(l), where l = 4 sqrt(sigma0^2 + 2 K age) is the scale the cloud reaches.
    A fixed point, iterated; converges in a few steps because l^1.15 grows slower than l^2."""
    K = 1.0
    for _ in range(60):
        l = 4.0 * math.sqrt(sigma0_m ** 2 + 2.0 * K * age_h * 3600.0)
        K = float(np.clip(factor * age.okubo_diffusivity_m2s(l), *age.OKUBO_K_BOUNDS_M2S))
    return K


def track_seed(t, n, rng, t0):
    """Positions and seed times of a moving discharge: (lon, lat, hours_before_t0) per particle."""
    tau = rng.uniform(0.0, t["discharge_h"], n)                 # hours after discharge start
    d_m = tau * 3600.0 * t["ship_speed_ms"]
    hd = math.radians(t["heading_deg"])
    coslat = math.cos(math.radians(t["release"][1]))
    lon = t["release"][0] + (d_m * math.sin(hd) + rng.normal(0, t["sigma0_m"], n)) / (
        age.KM_PER_DEG_LAT * 1e3 * coslat)
    lat = t["release"][1] + (d_m * math.cos(hd) + rng.normal(0, t["sigma0_m"], n)) / (
        age.KM_PER_DEG_LAT * 1e3)
    return lon, lat, t["age_h"] - tau


def simulate_ours(t, field, t0, n=2000, timestep_minutes=15):
    import ensemble as ens
    from step import integrate
    rng = np.random.default_rng(t["seed"])
    f = ens.PerturbedField(field, t["current_scale"])
    if t["kind"] == "patch":
        start = age.seed_cloud(t["release"][0], t["release"][1], n, sigma_m=t["sigma0_m"],
                               rng=rng)
        steps = int(round(t["age_h"] * 60 / timestep_minutes)) + 1
        hist, _ = integrate(start, t0 - timedelta(hours=t["age_h"]), f, steps,
                            timestep_minutes, direction="forward", wind_coeff=t["wind_coeff"],
                            diffusivity=t["K_m2s"], rng=rng)
        return hist[-1]
    lon, lat, hb = track_seed(t, n, rng, t0)
    # integrate in groups by seed time: 12 slices of the discharge
    out = []
    edges = np.linspace(hb.min(), hb.max() + 1e-9, 13)
    for a, b in zip(edges[:-1], edges[1:]):
        sel = (hb >= a) & (hb < b)
        if not sel.any():
            continue
        hstart = float((a + b) / 2)
        steps = max(int(round(hstart * 60 / timestep_minutes)), 0) + 1
        hist, _ = integrate(np.column_stack([lon[sel], lat[sel]]),
                            t0 - timedelta(hours=hstart), f, steps, timestep_minutes,
                            direction="forward", wind_coeff=t["wind_coeff"],
                            diffusivity=t["K_m2s"], rng=rng)
        out.append(hist[-1])
    return np.vstack(out)


def cmd_make(a):
    from fields import load_case_field
    d = TWINS / a.field
    d.mkdir(parents=True, exist_ok=True)
    field = load_case_field(a.field, repo_root=REPO)
    t0, anchor = case_anchor(a.field)
    truths = draw_truths(a.field, a.n, a.seed + FIELDS.index(a.field), getattr(field, "bbox", None),
                         anchor)
    features = {}
    tic = time.time()
    for t in truths:
        if t["generator"] != "ours":
            continue
        pos = simulate_ours(t, field, t0)
        feat = particles_to_feature(pos, t["id"])
        features[t["id"]] = feat
        print(f"  {t['id']}  {t['kind']:<5} age {t['age_h']:5.1f} h  K {t['K_m2s']:7.2f}  -> "
              + ("NOT VISIBLE" if feat is None else
                 f"{feat['properties']['area_km2']:.2f} km2 elong "
                 f"{feat['properties']['elongation']} {feat['properties']['discharge_class']}")
              + f"   [{time.time() - tic:.0f} s]", flush=True)
    (d / "truths.json").write_text(json.dumps({"field": a.field, "t0": t0.isoformat(),
                                               "truths": truths}, indent=1))
    (d / "features_ours.json").write_text(json.dumps(features))
    (d / "openoil_truth_request.json").write_text(json.dumps({
        "field": a.field, "t0": t0.isoformat().replace("+00:00", "Z"),
        "truths": [t for t in truths if t["generator"] == "openoil"]}, indent=1))
    print(f"wrote {d}  ({sum(1 for t in truths if t['generator'] == 'ours')} ours, "
          f"{sum(1 for t in truths if t['generator'] == 'openoil')} for OpenOil)")


# ---------------------------------------------------------------------------------------
# prepare: polygonise OpenOil truths, compute release points, write the E2 batch request
# ---------------------------------------------------------------------------------------

def candidate_hours():
    lo, hi, st = (float(x) for x in CANDIDATES.split(":"))
    return sorted({1.0, *[round(x, 6) for x in np.arange(lo, hi + 1e-9, st)]})


def load_features(d):
    feats = json.loads((d / "features_ours.json").read_text())
    oo = d / "openoil_truths.npz"
    if oo.exists():
        z = np.load(oo, allow_pickle=False)
        ids = [str(x) for x in z["ids"]]
        for k, tid in enumerate(ids):
            sel = z["owner"] == k
            feats[tid] = particles_to_feature(np.column_stack([z["lon"][sel], z["lat"][sel]]),
                                              tid)
    return feats


def cmd_prepare(a):
    from fields import load_case_field
    import coastline
    d = TWINS / a.field
    truths = json.loads((d / "truths.json").read_text())
    t0 = parse_ts(truths["t0"])
    feats = load_features(d)
    field = load_case_field(a.field, repo_root=REPO)
    land = coastline.is_land if coastline.available() else None
    ch = candidate_hours()
    cov = age.field_time_coverage(a.field, REPO)
    ch, _, _ = age.clip_candidates_to_coverage(ch, t0, cov)
    batch = []
    for t in truths["truths"]:
        f = feats.get(t["id"])
        if f is None:
            continue
        rel = age.control_release_points(field, f, t0, ch, seed=7, is_land=land)
        batch.append({"id": t["id"], "okubo_scale_m": age.slick_scale_m(f),
                      "release_points": [[round(x, 5), round(y, 5)] for x, y in rel]})
    (d / "features_all.json").write_text(json.dumps(feats))
    req = {"case": a.field, "t0": t0.isoformat().replace("+00:00", "Z"),
           "candidate_hours": ch, "batch": batch, "timestep_minutes": 15}
    (d / "age_batch_request.json").write_text(json.dumps(req, indent=1))
    print(f"prepared {len(batch)} visible twins ({len(truths['truths']) - len(batch)} not "
          f"visible) -> {d / 'age_batch_request.json'}")


# ---------------------------------------------------------------------------------------
# score: E1 curves per twin (expensive, parallel), E4, and stash everything
# ---------------------------------------------------------------------------------------

def _score_one(args):
    field_case, t0_iso, ch, feat, rel = args
    from fields import load_case_field
    field = load_case_field(field_case, repo_root=REPO)
    t0 = parse_ts(t0_iso)
    L, ad = age.slick_major_axis_km(feat)
    props = feat["properties"]
    band, sd = age.shear_dispersion_age(
        field, props["centroid"][0], props["centroid"][1], t0, L, ch,
        n_particles=SCORE_PARTICLES, n_members=SCORE_MEMBERS, seed=11,
        discharge_class="unknown", release_points=rel,
        observed_width_km=ad.get("bbox_width_km"), observed_bearing_deg=ad.get("orientation_deg"))
    _, td = age.track_age(feat, props.get("discharge_class"))
    return {"id": props["id"], "obs": {"L": L, "W": ad.get("bbox_width_km"),
                                       "B": ad.get("orientation_deg")},
            "discharge_class": props.get("discharge_class"),
            "curves_ours": sd.get("shape_curves"),
            "track_loglik": td.get("loglik"), "track_skipped": td.get("skipped")}


def cmd_score(a):
    from concurrent.futures import ProcessPoolExecutor
    d = TWINS / a.field
    req = json.loads((d / "age_batch_request.json").read_text())
    feats = json.loads((d / "features_all.json").read_text())
    done_path = d / "scored.json"
    done = json.loads(done_path.read_text()) if done_path.exists() else {}
    jobs = [(a.field, req["t0"], req["candidate_hours"], feats[b["id"]], b["release_points"])
            for b in req["batch"] if b["id"] not in done]
    print(f"scoring {len(jobs)} twins on {a.jobs} processes ({len(done)} already done)")
    tic = time.time()
    with ProcessPoolExecutor(max_workers=a.jobs) as ex:
        for r in ex.map(_score_one, jobs):
            done[r["id"]] = r
            done_path.write_text(json.dumps(done))
            print(f"  {r['id']}  [{time.time() - tic:.0f} s]", flush=True)


# ---------------------------------------------------------------------------------------
# calibrate: refit sigmas + weights from stored curves, leave-one-field-out
# ---------------------------------------------------------------------------------------

def load_all():
    rows = []
    for f in FIELDS:
        d = TWINS / f
        if not (d / "scored.json").exists():
            continue
        truths = {t["id"]: t for t in json.loads((d / "truths.json").read_text())["truths"]}
        req = json.loads((d / "age_batch_request.json").read_text())
        scored = json.loads((d / "scored.json").read_text())
        od = None
        odp = d / "opendrift_age_batch.npz"
        if odp.exists():
            z = np.load(odp, allow_pickle=False)
            od = {"ids": [str(x) for x in z["ids"]], "L": z["L_km"], "W": z["W_km"],
                  "B": z["bearing_deg"], "SF": z["surface_fraction"],
                  "ch": z["candidate_hours"]}
        for tid, s in scored.items():
            r = dict(s)
            r["truth"] = truths[tid]
            r["field"] = f
            r["ch"] = req["candidate_hours"]
            if od is not None and tid in od["ids"]:
                k = od["ids"].index(tid)
                r["curves_od"] = {"L": od["L"][k], "W": od["W"][k], "B": od["B"][k],
                                  "SF": od["SF"][k], "ch": od["ch"]}
            rows.append(r)
    return rows


def posterior_for(r, setting, p):
    """Rebuild one twin's posterior from stored curves under parameters `p` and a setting."""
    ll1 = ll2 = ll3 = None
    o = r["obs"]
    c = r.get("curves_ours")
    if setting in ("mixture", "cross_ours") and c and o["L"]:
        ll1 = age.shape_loglik(r["ch"], c["L_km"], c["W_km"], c["bearing_deg"], o["L"], o["W"],
                               o["B"], p["sigma_L"], p["sigma_W"], p["kappa"])
    od = r.get("curves_od")
    if setting in ("mixture", "cross_openoil") and od is not None and o["L"]:
        ll2 = age.shape_loglik(od["ch"], od["L"], od["W"], od["B"], o["L"], o["W"], o["B"],
                               p["sigma_L"], p["sigma_W"], p["kappa"])
        if setting == "mixture":
            ll3 = age.detectability_loglik(od["ch"], od["SF"])
    w = p["weights"]
    llt = None if r.get("track_loglik") is None else np.asarray(r["track_loglik"])
    patch, pu = AP.fuse([("shape", AP.mix_logliks([ll1, ll2]), w["shape"]),
                         ("detect", ll3, w["detect"])])
    track, tu = AP.fuse([("track", llt, w["track"]), ("detect", ll3, w["detect"])])
    patch = None if pu == ["detect"] else patch
    track = None if tu == ["detect"] else track
    dc = r.get("discharge_class")
    if dc == "acute":
        post = patch
    elif dc == "chronic":
        post = track
    else:
        post = AP.average_posteriors([patch, track])
    return AP.summarise(post, []), post


def settings_for(r):
    s = ["mixture"]
    if r["truth"]["generator"] == "openoil":
        s.append("cross_ours")
    if r["truth"]["generator"] == "ours" and r.get("curves_od") is not None:
        s.append("cross_openoil")
    return s


def evaluate(rows, p, setting):
    """Coverage, width, log score and refusal rate over `rows` under one setting."""
    cov, width, logs, pits, n_ref, n = [], [], [], [], 0, 0
    for r in rows:
        if setting not in settings_for(r):
            continue
        n += 1
        summ, post = posterior_for(r, setting, p)
        if post is None or summ["status"] != "ok":
            n_ref += 1
            continue
        t = r["truth"]["age_h"]
        lo, hi = summ["hpd80"]
        cov.append(lo <= t <= hi)
        width.append(math.log(hi / max(lo, 0.5)))
        k = int(np.argmin(np.abs(AP.AGE_GRID_H - t)))
        logs.append(math.log(max(post[k], 1e-12)))
        pits.append(AP.pit(post, t))
    return {"n": n, "answered": len(cov), "refused": n_ref,
            "coverage80": None if not cov else round(float(np.mean(cov)), 3),
            "median_log_width": None if not width else round(float(np.median(width)), 3),
            "mean_log_score": None if not logs else round(float(np.mean(logs)), 3),
            "pits": [round(x, 3) for x in pits]}


def fit(rows):
    """Grid search: sigmas on the CROSS settings; weights by coverage-penalised log score."""
    best = None
    for sL in (0.2, 0.3, 0.45, 0.65, 0.9):
        for sW in (0.35, 0.5, 0.75, 1.0):
            for kap in (0.0, 0.5, 1.0):
                for ws in (0.5, 0.75, 1.0):
                    for wt in (0.25, 0.5, 1.0):
                        p = {"sigma_L": sL, "sigma_W": sW, "kappa": kap,
                             "weights": {"shape": ws, "detect": 0.5, "track": wt,
                                         "surrogate": 0.0}}
                        score, ok = 0.0, True
                        for st in ("cross_ours", "cross_openoil"):
                            e = evaluate(rows, p, st)
                            if not e["answered"]:
                                continue
                            score += e["mean_log_score"] - 10.0 * abs(e["coverage80"] - 0.80)
                        if best is None or score > best[0]:
                            best = (score, p)
    return best[1]


def cmd_calibrate(a):
    rows = load_all()
    fields = sorted({r["field"] for r in rows})
    print(f"{len(rows)} scored twins across {len(fields)} fields")
    if len(fields) < 2:
        raise SystemExit("need at least two scored fields for leave-one-field-out")
    held = {st: [] for st in ("mixture", "cross_ours", "cross_openoil")}
    for f in fields:
        p = fit([r for r in rows if r["field"] != f])
        test = [r for r in rows if r["field"] == f]
        for st in held:
            e = evaluate(test, p, st)
            e["field"] = f
            held[st].append(e)
        print(f"  held out {f}: fitted sigma_L {p['sigma_L']} sigma_W {p['sigma_W']} "
              f"kappa {p['kappa']} w {p['weights']}")
    final = fit(rows)
    summary = {}
    for st, es in held.items():
        ans = sum(e["answered"] for e in es)
        cov = sum((e["coverage80"] or 0) * e["answered"] for e in es)
        summary[st] = {"n": sum(e["n"] for e in es), "answered": ans,
                       "refused": sum(e["refused"] for e in es),
                       "coverage80_heldout": None if not ans else round(cov / ans, 3),
                       "per_field": es}
    cal = {"sigma_L": final["sigma_L"], "sigma_W": final["sigma_W"], "kappa": final["kappa"],
           "weights": final["weights"],
           "coverage80": summary["mixture"]["coverage80_heldout"],
           "coverage80_cross": {k: summary[k]["coverage80_heldout"]
                                for k in ("cross_ours", "cross_openoil")},
           "n_twins": len(rows), "fields": fields,
           "method": "leave-one-field-out grid search; sigmas fitted on cross-model twins only",
           "fitted": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}
    age.CALIBRATION_PATH.write_text(json.dumps(cal, indent=1))
    (TWINS / "calibration_report.json").write_text(json.dumps(summary, indent=1))
    print(json.dumps({k: {kk: vv for kk, vv in v.items() if kk != "per_field"}
                      for k, v in summary.items()}, indent=1))
    print(f"wrote {age.CALIBRATION_PATH}")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    m = sub.add_parser("make")
    m.add_argument("--field", required=True, choices=FIELDS)
    m.add_argument("--n", type=int, default=24)
    m.add_argument("--seed", type=int, default=2026)
    pr = sub.add_parser("prepare")
    pr.add_argument("--field", required=True, choices=FIELDS)
    sc = sub.add_parser("score")
    sc.add_argument("--field", required=True, choices=FIELDS)
    sc.add_argument("--jobs", type=int, default=7)
    sub.add_parser("calibrate")
    a = ap.parse_args(argv)
    {"make": cmd_make, "prepare": cmd_prepare, "score": cmd_score,
     "calibrate": cmd_calibrate}[a.cmd](a)
    return 0


if __name__ == "__main__":
    sys.exit(main())
