#!/usr/bin/env python3
"""
Stage 4 helper: keep `verification/<case>.json` honest and publish it. Owner: Akshat.

    python scripts/scaffold_verification.py --check                # what is still unwritten
    python scripts/scaffold_verification.py --update --all         # refresh udgam_result only
    python scripts/scaffold_verification.py --case case-x          # create a draft from scratch
    python scripts/scaffold_verification.py --publish case-x       # add `verify` + build + validate

WHAT THIS WRITES, AND WHAT IT REFUSES TO WRITE
`udgam_result` is **our own output** — origin radii, centroid, release window, the MMSIs on the
suspect cards, whether Stage 3 abstained — so it is filled in mechanically from the bundle, and
`--update` refreshes it in place after a re-score. Nothing else is touched.

`official_finding` and `assessment` are **not generated by this script, ever** (Master §6.8:
"HUMAN-WRITTEN PROSE. Never generated."). They are the researched finding plus a judgement about
our own result, and a verdict a script invented would be exactly the thing Part 1.5 forbids. It
never reads `docs/ANSWERS.md`. (D43 records the one-off exception: the six live cases' assessment
prose was drafted by Claude on 14 Sept at Akshat's instruction, from the finding already in the
file — by hand, not by this script, and still his to edit.)

`--publish` refuses a file that carries a TODO **anywhere** in it, not only in the fields someone
remembered to list — see `placeholders()`.

`verify` reaches a case only through `--publish`, which adds the act, runs build_case and then
the validator — so a half-written verification cannot reach a bundle by accident.
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PY = sys.executable
TODO = "TODO (Akshat)"
VERDICTS = ("hit", "partial", "miss", "not_applicable")

# Stamped onto `_status` by --publish. `_status` is a note to ourselves: an underscore key, not
# part of the frozen §6.8 schema, never rendered by the Verify screen. It is rewritten on publish
# because the drafts carry "DO NOT COMMIT until Stage 3 has scored this case", which stops being
# true the moment the file is on screen.
STATUS_PUBLISHED = (
    "PUBLISHED — this file is on the Verify screen. official_finding is researched prose; "
    "udgam_result is regenerated from the bundle by scripts/scaffold_verification.py (never by "
    "hand); assessment is the verdict on our own result — for the six live cases it was drafted "
    "14 Sept under Master D43 and is Akshat's to edit and own. Re-run --publish after any edit."
)


def vpath(case_id):
    return REPO / "verification" / f"{case_id}.json"


def traced_cases():
    index = json.loads((REPO / "cases" / "index.json").read_text(encoding="utf-8"))
    return [c for c in index["cases"] if (REPO / "cases" / c / "origin.json").exists()]


def udgam_result(case_id):
    """Our own result, from the bundle as it stands right now."""
    case_dir = REPO / "cases" / case_id
    o = json.loads((case_dir / "origin.json").read_text(encoding="utf-8"))
    lon, lat = o["centroid"]
    method = o.get("time_window_method", "unknown")
    summary = (
        f"Origin cloud centred at {abs(lat):.4f}° {'S' if lat < 0 else 'N'}, "
        f"{abs(lon):.4f}° {'W' if lon < 0 else 'E'}; half the ensemble lands within "
        f"{o['radius_50_km']} km and nine in ten within {o['radius_90_km']} km. Release window "
        f"{o['time_window'][0]} to {o['time_window'][1]} ({method})."
    )
    if o.get("abstain"):
        summary += " Stage 2 flagged the cloud as too diffuse to attribute."

    top, abstained = [], False
    s_path = case_dir / "suspects.json"
    if s_path.exists():
        s = json.loads(s_path.read_text(encoding="utf-8"))
        top = [x["mmsi"] for x in s.get("suspects", []) if x.get("mmsi")]
        abstained = bool(s.get("abstained"))
        f = s.get("funnel") or {}
        if f:
            summary += (
                f" Stage 3 funnel {f.get('in_region')} → {f.get('in_window')} → "
                f"{f.get('plausible')} → {f.get('scored')}."
            )
        if abstained and s.get("abstain_reason"):
            summary += f" Abstained: {s['abstain_reason']}"
        n_dark = len(s.get("dark_vessels") or [])
        if n_dark:
            summary += (
                f" {n_dark} radar contact(s) near the slick or origin carried no matching AIS "
                f"broadcast at acquisition time."
            )
    return {"origin_summary": summary, "top_suspects": top, "abstained": abstained}


def blank_doc(case_id):
    return {
        "official_finding": {
            "summary": TODO,
            "responsible_parties": [],
            "source_name": TODO,
            "source_url": "",
            "source_type": "none",
            "volume_reported": TODO,
            "caveat": TODO,
        },
        "udgam_result": udgam_result(case_id),
        "assessment": {
            "verdict": TODO,
            "explanation": TODO,
            "what_would_have_helped": TODO,
        },
    }


def placeholders(node, path=""):
    """Every string still carrying a TODO marker, by JSON path.

    Field-by-field checks kept missing things: `official_finding.caveat` was never checked, yet
    VerifyScreen.tsx renders it — a publish would have put "TODO, HUMAN PROSE (Akshat). Facts to
    weigh: …" on the demo screen. So the whole document is walked instead, and the next field
    someone adds is covered for free. Underscore keys (`_status`) are skipped: they are notes to
    ourselves, not part of §6.8 and never rendered.
    """
    if isinstance(node, dict):
        return [p for k, v in node.items() if not str(k).startswith("_")
                for p in placeholders(v, f"{path}.{k}" if path else k)]
    if isinstance(node, list):
        return [p for i, v in enumerate(node) for p in placeholders(v, f"{path}[{i}]")]
    if isinstance(node, str) and "TODO" in node:
        return [path]
    return []


def outstanding(doc):
    """What still has to be written by hand before this file may ship."""
    todo = []
    of = doc.get("official_finding") or {}
    a = doc.get("assessment") or {}
    if not str(of.get("source_url") or "").strip():
        todo.append("official_finding.source_url is empty")
    if a.get("verdict") not in VERDICTS:
        todo.append(f"assessment.verdict is {a.get('verdict')!r}, not one of {'|'.join(VERDICTS)}")
    for k in ("explanation", "what_would_have_helped"):
        if not str(a.get(k) or "").strip():
            todo.append(f"assessment.{k} is empty")
    todo += [f"{p} still says TODO" for p in placeholders(doc)]
    return todo


def write(path, doc):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")


def cmd_create(case_id, force):
    path = vpath(case_id)
    if path.exists() and not force:
        raise SystemExit(f"{path.relative_to(REPO)} already exists — use --update, or --force")
    write(path, blank_doc(case_id))
    print(f"wrote {path.relative_to(REPO)} (official_finding + assessment left for you)")


def cmd_update(case_id):
    path = vpath(case_id)
    if not path.exists():
        return cmd_create(case_id, force=False)
    doc = json.loads(path.read_text(encoding="utf-8"))
    doc["udgam_result"] = udgam_result(case_id)
    write(path, doc)
    left = outstanding(doc)
    print(f"{case_id}: udgam_result refreshed from the bundle · "
          + ("ready to publish" if not left else f"{len(left)} field(s) still to write"))


def cmd_check():
    rows = []
    for case_id in traced_cases():
        path = vpath(case_id)
        if not path.exists():
            rows.append((case_id, "no file", ["run --update to scaffold one"]))
            continue
        doc = json.loads(path.read_text(encoding="utf-8"))
        acts = json.loads((REPO / "cases" / case_id / "meta.json").read_text(encoding="utf-8"))
        left = outstanding(doc)
        state = ("published" if "verify" in acts["acts_available"]
                 else "ready to publish" if not left else "needs writing")
        rows.append((case_id, state, left))
    w = max(len(r[0]) for r in rows)
    for case_id, state, left in rows:
        print(f"{case_id:<{w}}  {state}")
        for item in left:
            print(f"{'':<{w}}    - {item}")
    print("\nVerify appears in the demo only after: fill the file, then "
          "scripts/scaffold_verification.py --publish <case>")


def cmd_publish(case_id):
    path = vpath(case_id)
    if not path.exists():
        raise SystemExit(f"{path.relative_to(REPO)} does not exist")
    doc = json.loads(path.read_text(encoding="utf-8"))
    left = outstanding(doc)
    if left:
        raise SystemExit(
            f"{case_id} is not ready — a verification.json is a claim on screen:\n  "
            + "\n  ".join(left))
    doc["udgam_result"] = udgam_result(case_id)
    doc["_status"] = STATUS_PUBLISHED
    write(path, doc)

    meta_path = REPO / "cases" / case_id / "meta.json"
    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    if "verify" not in meta["acts_available"]:
        meta["acts_available"].append("verify")
        meta_path.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
        print(f"added 'verify' to {case_id}/meta.json")
    for cmd in (
        [PY, REPO / "pipeline" / "export" / "build_case.py", "--case", case_id,
         "--stage", "verify"],
        [PY, REPO / "scripts" / "validate_case.py", REPO / "cases" / case_id],
        [PY, REPO / "scripts" / "sync_web_cases.py"],
    ):
        print(f"\n$ {' '.join(str(c) for c in cmd)}", flush=True)
        if subprocess.run([str(c) for c in cmd], cwd=REPO).returncode != 0:
            raise SystemExit("step failed — nothing further was published")


def main():
    ap = argparse.ArgumentParser(description="Scaffold, refresh and publish verification.json")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--case", help="create a draft for this case")
    g.add_argument("--all", action="store_true", help="every indexed case with a trace")
    g.add_argument("--check", action="store_true", help="report what is still unwritten")
    g.add_argument("--publish", metavar="CASE", help="add `verify`, build and validate")
    ap.add_argument("--update", action="store_true",
                    help="with --case/--all: refresh udgam_result in place, touching nothing else")
    ap.add_argument("--force", action="store_true", help="overwrite an existing draft")
    a = ap.parse_args()

    if a.check:
        cmd_check()
    elif a.publish:
        cmd_publish(a.publish)
    elif a.all:
        for case_id in traced_cases():
            cmd_update(case_id) if a.update else cmd_create(case_id, a.force)
    else:
        cmd_update(a.case) if a.update else cmd_create(a.case, a.force)


if __name__ == "__main__":
    main()
